name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure a full clone (not shallow)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17" # Or 21 if your project is compatible
          distribution: "temurin"
          cache: gradle
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          # You need to specify the build-tools and platform versions you need
          build-tools-version: "34.0.0" # Replace with your required version
          platform-tools-version: "34.0.5"
          compile-sdk-version: "34" # Replace with your required version
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clean with Gradle
        run: ./gradlew clean
      - name: Build with Gradle
        run: ./gradlew build