name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure a full clone (not shallow)
      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install
      - name: Check Git LFS Version
        run: git lfs version
      - name: Configure Git LFS Authentication
        run: |
          git config --global credential.helper store
          echo "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com" > ~/.git-credentials
          git config --global credential.https://github.com.helper store
      - name: Fetch Git LFS objects
        run: git lfs fetch --all --prune # Fetch all LFS objects and prune old ones
      - name: Check .gitattributes
        run: ls -la .gitattributes
      - name: Check LFS Files
        run: |
          ls -la app/src/main/res/drawable-hdpi/ic_connected.png
          ls -la app/src/main/res/drawable-xxhdpi/ic_settings.png
          ls -la app/src/main/res/drawable-xhdpi/ic_settings.png
      - name: List drawable contents
        run: ls -la app/src/main/res/drawable-hdpi app/src/main/res/drawable-xhdpi app/src/main/res/drawable-xxhdpi
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17" # Or 21 if your project is compatible
          distribution: "temurin"
          cache: gradle
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          # You need to specify the build-tools and platform versions you need
          build-tools-version: "34.0.0" # Replace with your required version
          platform-tools-version: "34.0.5"
          compile-sdk-version: "34" # Replace with your required version
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clean with Gradle
        run: ./gradlew clean
      - name: Build with Gradle
        run: ./gradlew build